/*
Check the error

What error will be generated by the given code?

#include <iostream>
using namespace std;
void func(int a) {
    int b = a;
    b = b + 10;
}

int main() {
    int a = 10;
    func(a);
    cout << b << endl;
}

1. a is not declared in the scope.
2. b is not declared in the scope.                  // At Line Number 16 b, Because b is Only Accessable in func function Not Accessable Outside the Function
3. a and b both are not declared in this scope.
4. None of the above.

Solution Description : The scope of b is limited to the function only but in the question 
                    we are trying to access it inside the main function, that's why error 
                    will be generated.
*/

/*
What will be the output of the following code ?

#include <iostream>
using namespace std;

void func(int a) {
    int b = 10;
    a = b + 10;
    cout << a << " ";
}

int main() {
    int a = 10;
    func(a);
    cout << a << " ";
}


1. 20 20
2. 20 10                    // Correct, Because First Compiler Goes for func because func is Called After that it Prints 20 and return to the main function and Execute a which value is 10
3. 10 20
4. 20 30
Solution Description : The main function calls the "func" function with the value of "a" 
                        as an argument.


Inside the "func" function, the value of "a" is changed and printed, 
but this change does not affect the value of "a" in the main function.
Finally, the value of "a" in the main function is printed.
*/